Fix test failure
This fixes the test failures in the jenkins build which causes the error
java.lang.NoClassDefFoundError: Could not initialize class
org.wso2.carbon.context.PrivilegedCarbonContext